name: clippy

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Clippy
        env:
          CARGO_INCREMENTAL: "0"
        run: cargo clippy --workspace --all-targets --all-features --message-format short -- -D warnings
